### PR TITLE
fix: combine endpoint to revert RSV to VRS

### LINKED ISSUE #14: Verify the RSV signature
Verify the implementation for the signature format.

### PR DESCRIPTION
**Pull request by rllola**
The implementation was only formatting to VRS (blockstack signature format) only if it was starting with `01`. However the V value can be 4 differents value : `00`, `01`, `02` or `03`.

The test was failing randomly because of this.

This PR :
- [x] update the rosetta `combine` endpoint implementation to match the spec (https://www.rosetta-api.org/docs/models/SignatureType.html)
- [x] update the tests to create rosetta compliant signature

### CODE REVIEW

File: src/tests-rosetta/api.ts [hunk 1]
```diff
@@ -1981,7 +1989,7 @@ describe('Rosetta API', () => {
           },
           signature_type: 'ecdsa',
```
Comment (rllola) [inline src/tests-rosetta/api.ts]: `siganture_type` should probably always match `ecdsa_recovery` (https://www.rosetta-api.org/docs/models/SignatureType.html) ?

The other type is actually not supported.

File: src/tests-rosetta/api.ts [hunk 2]
```diff
@@ -1867,7 +1867,15 @@ describe('Rosetta API', () => {
     signer.signOrigin(createStacksPrivateKey(testnetKeys[0].secretKey));
     const signedSerializedTx = signer.transaction.serialize().toString('hex');
 
-    const signature: MessageSignature = getSignature(signer.transaction) as MessageSignature;
+    let signature = getSignature(signer.transaction) as MessageSignature;
+
+    console.log(signature.data)
```
Comment (jleni) [inline src/tests-rosetta/api.ts]: Can we remove this console.log from here?

**Review by jleni — CHANGES_REQUESTED** [review]

File: src/tests-rosetta/api.ts [hunk 3]
```diff
@@ -1867,7 +1867,15 @@ describe('Rosetta API', () => {
...
+
+    // Rosetta ecdsa_recovery is r + s + v
+    // see https://www.rosetta-api.org/docs/models/SignatureType.html 
+    let sig_rsv = signature.data.slice(2) + signature.data.slice(0, 2);
+
+    console.log(sig_rsv)
```
Comment (jleni) [inline src/tests-rosetta/api.ts]: same

**Review by jleni — CHANGES_REQUESTED** [review]

**Comment by jleni** [comment]
@rllola 
There is this ugly conflict here

File: src/tests-rosetta/api.ts [hunk 4]
```diff
@@ -1871,7 +1872,7 @@ describe('Rosetta API', () => {
     signer.signOrigin(createStacksPrivateKey(testnetKeys[0].secretKey));
     const signedSerializedTx = signer.transaction.serialize().toString('hex');
 
-    const signature: MessageSignature = getSignature(signer.transaction) as MessageSignature;
+    let signature = getSignature(signer.transaction) as MessageSignature;
```
Comment (rllola) [inline src/tests-rosetta/api.ts]: Should be kept as `const`

**Comment by rllola** [comment]
I have rebased the blockstack modification. The PR now only include the changes to enforce `ecdsa_recovery` signature type as other signature types are not supported.
